import fs from "node:fs";
import path from "node:path";

type Json = Record<string, unknown>;

function stableStringify(value: unknown): string {
  const seen = new WeakSet<object>();
  const sort = (v: unknown): unknown => {
    if (Array.isArray(v)) return v.map(sort);
    if (v && typeof v === "object") {
      if (seen.has(v as object)) return null;
      seen.add(v as object);
      const out: Record<string, unknown> = {};
      for (const k of Object.keys(v as Record<string, unknown>).sort()) {
        out[k] = sort((v as Record<string, unknown>)[k]);
      }
      return out;
    }
    return v;
  };
  return JSON.stringify(sort(value), null, 2) + "\n";
}

const report: Json = {
  artifact_version: "1.0.0",
  generated_at_utc: "STATIC_FOR_DETERMINISM",
  source_of_truth: {
    flutter_files: [
      "lib/models/lead.dart",
      "lib/models/dashboard_stats.dart",
      "lib/models/auth_user.dart",
      "lib/models/notification_event.dart",
      "lib/services/api_service.dart",
    ],
    backend_files: [
      "src/modules/auth/auth.router.ts",
      "src/modules/auth/auth.service.ts",
      "src/modules/auth/auth.schema.ts",
      "src/modules/leads/leads.router.ts",
      "src/modules/leads/leads.service.ts",
      "src/modules/leads/leads.schema.ts",
      "src/shared/utils/leadSerializer.ts",
      "src/modules/dashboard/dashboard.router.ts",
      "src/modules/dashboard/dashboard.service.ts",
      "src/modules/notifications/notifications.router.ts",
      "src/modules/notifications/notifications.service.ts",
      "src/modules/tracking/tracking.router.ts",
      "src/modules/letters/letters.router.ts",
    ],
  },
  endpoints: [
    {
      domain: "auth",
      name: "login",
      method: "POST",
      path: "/v1/auth/login",
      auth_required: false,
      request_schema: {
        email: { type: "string", required: true },
        password: { type: "string", required: true },
      },
      response_schema: {
        id: { type: "string", required: true },
        email: { type: "string", required: true },
        name: { type: "string", required: true },
        role: { type: "string", required: true, enum: ["admin", "reviewer"] },
        access_token: { type: "string", required: true },
        refresh_token: { type: "string", required: true },
        expires_at: { type: "string", format: "iso8601", required: true },
      },
      serializer_source: "src/modules/auth/auth.service.ts:34-43",
      router_source: "src/modules/auth/auth.router.ts:8-11",
    },
    {
      domain: "auth",
      name: "logout",
      method: "POST",
      path: "/v1/auth/logout",
      auth_required: true,
      request_schema: {
        refresh_token: { type: "string", required: false },
      },
      response_schema: { status_code: 204 },
      serializer_source: "src/modules/auth/auth.service.ts:46-54",
      router_source: "src/modules/auth/auth.router.ts:13-20",
    },
    {
      domain: "auth",
      name: "refresh",
      method: "POST",
      path: "/v1/auth/refresh",
      auth_required: false,
      request_schema: {
        refresh_token: { type: "string", required: true },
      },
      response_schema: {
        access_token: { type: "string", required: true },
        expires_at: { type: "string", format: "iso8601", required: true },
      },
      serializer_source: "src/modules/auth/auth.service.ts:56-62",
      router_source: "src/modules/auth/auth.router.ts:22-25",
    },
    {
      domain: "leads",
      name: "list",
      method: "GET",
      path: "/v1/leads",
      auth_required: true,
      request_schema: {
        query: {
          state: { type: "string", required: false, enum: ["CA", "FL"] },
          county: { type: "string", required: false },
          status: { type: "string", required: false },
          page: { type: "integer", required: true, default: 1 },
          page_size: { type: "integer", required: true, default: 50, max: 200 },
        },
      },
      response_schema: { type: "array", items: "Lead" },
      serializer_source: "src/shared/utils/leadSerializer.ts:15-55",
      router_source: "src/modules/leads/leads.router.ts:8-11",
    },
    {
      domain: "leads",
      name: "detail",
      method: "GET",
      path: "/v1/leads/:id",
      auth_required: true,
      request_schema: { params: { id: { type: "string", required: true } } },
      response_schema: { type: "Lead" },
      serializer_source: "src/shared/utils/leadSerializer.ts:15-55",
      router_source: "src/modules/leads/leads.router.ts:13-16",
    },
    {
      domain: "letters",
      name: "queue",
      method: "GET",
      path: "/v1/letters/queue",
      auth_required: true,
      request_schema: {
        query: {
          state: { type: "string", required: false, enum: ["CA", "FL"] },
          county: { type: "string", required: false },
          status: { type: "string", required: false },
          page: { type: "integer", required: false, default: 1 },
          page_size: { type: "integer", required: false, default: 50, max: 200 },
        },
      },
      response_schema: { type: "array", items: "Lead" },
      serializer_source: "src/shared/utils/leadSerializer.ts:15-55",
      router_source: "src/modules/letters/letters.router.ts:18-22",
    },
    {
      domain: "leads",
      name: "approve",
      method: "POST",
      path: "/v1/leads/:id/approve",
      auth_required: true,
      request_schema: { params: { id: { type: "string", required: true } }, body: {} },
      response_schema: { type: "Lead" },
      serializer_source: "src/modules/leads/leads.service.ts:68-90",
      router_source: "src/modules/leads/leads.router.ts:18-21",
    },
    {
      domain: "leads",
      name: "reject",
      method: "POST",
      path: "/v1/leads/:id/reject",
      auth_required: true,
      request_schema: {
        params: { id: { type: "string", required: true } },
        body: { reason: { type: "string", required: false } },
      },
      response_schema: { type: "Lead" },
      serializer_source: "src/modules/leads/leads.service.ts:92-112",
      router_source: "src/modules/leads/leads.router.ts:23-27",
    },
    {
      domain: "leads",
      name: "hold",
      method: "POST",
      path: "/v1/leads/:id/hold",
      auth_required: true,
      request_schema: {
        params: { id: { type: "string", required: true } },
        body: { reason: { type: "string", required: false } },
      },
      response_schema: { type: "Lead" },
      serializer_source: "src/modules/leads/leads.service.ts:114-131",
      router_source: "src/modules/leads/leads.router.ts:29-33",
    },
    {
      domain: "leads",
      name: "clear_legal_review",
      method: "POST",
      path: "/v1/leads/:id/clear-legal-review",
      auth_required: true,
      request_schema: {
        params: { id: { type: "string", required: true } },
        body: { legal_review_cleared: { type: "boolean", required: false, default: true } },
      },
      response_schema: { type: "Lead" },
      serializer_source: "src/modules/leads/leads.service.ts:133-146",
      router_source: "src/modules/leads/leads.router.ts:35-40",
    },
    {
      domain: "leads",
      name: "notes",
      method: "POST",
      path: "/v1/leads/:id/notes",
      auth_required: true,
      request_schema: {
        params: { id: { type: "string", required: true } },
        body: { notes: { type: "string", required: true } },
      },
      response_schema: { type: "Lead" },
      serializer_source: "src/modules/leads/leads.service.ts:148-153",
      router_source: "src/modules/leads/leads.router.ts:42-46",
    },
    {
      domain: "dashboard",
      name: "stats",
      method: "GET",
      path: "/v1/dashboard/stats",
      auth_required: true,
      request_schema: {},
      response_schema: {
        total_leads: "int",
        pending_approval: "int",
        flagged_legal_review: "int",
        letters_sent: "int",
        letters_delivered: "int",
        letters_returned: "int",
        total_surplus_amount: "double",
        average_surplus_amount: "double",
        leads_by_state: "map",
        leads_by_status: "map",
        generated_at: "iso8601",
      },
      serializer_source: "src/modules/dashboard/dashboard.service.ts:11-67",
      router_source: "src/modules/dashboard/dashboard.router.ts:6-10",
    },
    {
      domain: "notifications",
      name: "list",
      method: "GET",
      path: "/v1/notifications",
      auth_required: true,
      request_schema: {},
      response_schema: { type: "array", items: "NotificationEvent" },
      serializer_source: "src/modules/notifications/notifications.service.ts:7-21",
      router_source: "src/modules/notifications/notifications.router.ts:9-12",
    },
    {
      domain: "notifications",
      name: "read",
      method: "POST",
      path: "/v1/notifications/:id/read",
      auth_required: true,
      request_schema: { params: { id: { type: "uuid", required: true } } },
      response_schema: { status_code: 204 },
      serializer_source: "src/modules/notifications/notifications.service.ts:23-25",
      router_source: "src/modules/notifications/notifications.router.ts:14-18",
    },
    {
      domain: "notifications",
      name: "read_all",
      method: "POST",
      path: "/v1/notifications/read-all",
      auth_required: true,
      request_schema: {},
      response_schema: { status_code: 204 },
      serializer_source: "src/modules/notifications/notifications.service.ts:27-29",
      router_source: "src/modules/notifications/notifications.router.ts:20-23",
    },
    {
      domain: "tracking",
      name: "list",
      method: "GET",
      path: "/v1/tracking",
      auth_required: true,
      request_schema: {},
      response_schema: {
        type: "array",
        items: {
          id: "string",
          lead_id: "string",
          event: "string",
          timestamp: "iso8601",
          description: "string|null",
        },
      },
      serializer_source: "src/modules/tracking/tracking.router.ts:9-23",
      router_source: "src/modules/tracking/tracking.router.ts:41-47",
    },
    {
      domain: "tracking",
      name: "detail",
      method: "GET",
      path: "/v1/tracking/:id",
      auth_required: true,
      request_schema: { params: { id: { type: "string", required: true } } },
      response_schema: {
        id: "string",
        lead_id: "string",
        event: "string",
        timestamp: "iso8601",
        description: "string|null",
      },
      serializer_source: "src/modules/tracking/tracking.router.ts:9-23",
      router_source: "src/modules/tracking/tracking.router.ts:49-54",
    },
  ],
  flutter_models: [
    {
      flutter_file: "lib/models/auth_user.dart",
      model: "AuthUser",
      fields: [
        { field_name: "id", expected_type: "String", nullable: false, backend_response_key: "id", backend_source: "src/modules/auth/auth.service.ts:36", notes: "direct" },
        { field_name: "email", expected_type: "String", nullable: false, backend_response_key: "email", backend_source: "src/modules/auth/auth.service.ts:37", notes: "direct" },
        { field_name: "name", expected_type: "String", nullable: false, backend_response_key: "name", backend_source: "src/modules/auth/auth.service.ts:38", notes: "direct" },
        { field_name: "role", expected_type: "String", nullable: false, backend_response_key: "role", backend_source: "src/modules/auth/auth.service.ts:39", notes: "enum mapped to admin|reviewer" },
        { field_name: "accessToken", expected_type: "String", nullable: false, backend_response_key: "access_token", backend_source: "src/modules/auth/auth.service.ts:40", notes: "jwt string" },
        { field_name: "refreshToken", expected_type: "String", nullable: true, backend_response_key: "refresh_token", backend_source: "src/modules/auth/auth.service.ts:41", notes: "uuid string" },
        { field_name: "expiresAt", expected_type: "DateTime", nullable: false, backend_response_key: "expires_at", backend_source: "src/modules/auth/auth.service.ts:42", notes: "ISO8601" },
      ],
    },
    {
      flutter_file: "lib/models/dashboard_stats.dart",
      model: "DashboardStats",
      fields: [
        { field_name: "totalLeads", expected_type: "int", nullable: false, backend_response_key: "total_leads", backend_source: "src/modules/dashboard/dashboard.service.ts:52", notes: "num->int in flutter" },
        { field_name: "pendingApproval", expected_type: "int", nullable: false, backend_response_key: "pending_approval", backend_source: "src/modules/dashboard/dashboard.service.ts:53", notes: "num->int" },
        { field_name: "flaggedLegalReview", expected_type: "int", nullable: false, backend_response_key: "flagged_legal_review", backend_source: "src/modules/dashboard/dashboard.service.ts:54", notes: "num->int" },
        { field_name: "lettersSent", expected_type: "int", nullable: false, backend_response_key: "letters_sent", backend_source: "src/modules/dashboard/dashboard.service.ts:55", notes: "num->int" },
        { field_name: "lettersDelivered", expected_type: "int", nullable: false, backend_response_key: "letters_delivered", backend_source: "src/modules/dashboard/dashboard.service.ts:56", notes: "num->int" },
        { field_name: "lettersReturned", expected_type: "int", nullable: false, backend_response_key: "letters_returned", backend_source: "src/modules/dashboard/dashboard.service.ts:57", notes: "num->int" },
        { field_name: "totalSurplusAmount", expected_type: "double", nullable: false, backend_response_key: "total_surplus_amount", backend_source: "src/modules/dashboard/dashboard.service.ts:58", notes: "num->double" },
        { field_name: "averageSurplusAmount", expected_type: "double", nullable: false, backend_response_key: "average_surplus_amount", backend_source: "src/modules/dashboard/dashboard.service.ts:59", notes: "num->double" },
        { field_name: "leadsByState", expected_type: "Map<String,StateStats>", nullable: false, backend_response_key: "leads_by_state", backend_source: "src/modules/dashboard/dashboard.service.ts:27-33,60", notes: "contains count,total_surplus" },
        { field_name: "leadsByStatus", expected_type: "Map<String,int>", nullable: false, backend_response_key: "leads_by_status", backend_source: "src/modules/dashboard/dashboard.service.ts:35-49,61", notes: "keys must match LeadStatus.name values" },
        { field_name: "generatedAt", expected_type: "DateTime", nullable: false, backend_response_key: "generated_at", backend_source: "src/modules/dashboard/dashboard.service.ts:62", notes: "ISO8601" },
      ],
    },
    {
      flutter_file: "lib/models/notification_event.dart",
      model: "NotificationEvent",
      fields: [
        { field_name: "id", expected_type: "String", nullable: false, backend_response_key: "id", backend_source: "src/modules/notifications/notifications.service.ts:13", notes: "direct" },
        { field_name: "type", expected_type: "String(enum name)", nullable: false, backend_response_key: "type", backend_source: "src/modules/notifications/notifications.service.ts:14", notes: "must equal NotificationEventType.name" },
        { field_name: "leadId", expected_type: "String", nullable: false, backend_response_key: "lead_id", backend_source: "src/modules/notifications/notifications.service.ts:15", notes: "direct" },
        { field_name: "leadOwnerName", expected_type: "String", nullable: true, backend_response_key: "lead_owner_name", backend_source: "src/modules/notifications/notifications.service.ts:16", notes: "nullable" },
        { field_name: "message", expected_type: "String", nullable: true, backend_response_key: "message", backend_source: "src/modules/notifications/notifications.service.ts:17", notes: "nullable" },
        { field_name: "createdAt", expected_type: "DateTime", nullable: false, backend_response_key: "created_at", backend_source: "src/modules/notifications/notifications.service.ts:18", notes: "ISO8601" },
        { field_name: "isRead", expected_type: "bool", nullable: false, backend_response_key: "is_read", backend_source: "src/modules/notifications/notifications.service.ts:19", notes: "default false in flutter" },
      ],
    },
    {
      flutter_file: "lib/models/lead.dart",
      model: "Lead",
      fields: [
        { field_name: "id", expected_type: "String", nullable: false, backend_response_key: "id", backend_source: "src/shared/utils/leadSerializer.ts:17", notes: "direct" },
        { field_name: "parcelNumber", expected_type: "String", nullable: false, backend_response_key: "parcel_number", backend_source: "src/shared/utils/leadSerializer.ts:18", notes: "flutter fallback parcel_id supported" },
        { field_name: "ownerName", expected_type: "String", nullable: false, backend_response_key: "owner_name", backend_source: "src/shared/utils/leadSerializer.ts:19", notes: "direct" },
        { field_name: "ownerPhone", expected_type: "String", nullable: true, backend_response_key: "owner_phone", backend_source: "src/shared/utils/leadSerializer.ts:20", notes: "nullable" },
        { field_name: "ownerEmail", expected_type: "String", nullable: true, backend_response_key: "owner_email", backend_source: "src/shared/utils/leadSerializer.ts:21", notes: "nullable" },
        { field_name: "propertyAddress", expected_type: "String", nullable: false, backend_response_key: "property_address", backend_source: "src/shared/utils/leadSerializer.ts:22", notes: "direct" },
        { field_name: "mailingAddress", expected_type: "String", nullable: false, backend_response_key: "mailing_address", backend_source: "src/shared/utils/leadSerializer.ts:23", notes: "direct" },
        { field_name: "city", expected_type: "String", nullable: false, backend_response_key: "city", backend_source: "src/shared/utils/leadSerializer.ts:24", notes: "direct" },
        { field_name: "county", expected_type: "String", nullable: false, backend_response_key: "county", backend_source: "src/shared/utils/leadSerializer.ts:25", notes: "direct" },
        { field_name: "state", expected_type: "String(CA|FL)", nullable: false, backend_response_key: "state", backend_source: "src/shared/utils/leadSerializer.ts:26", notes: "abbr expected by flutter" },
        { field_name: "zip", expected_type: "String", nullable: false, backend_response_key: "zip", backend_source: "src/shared/utils/leadSerializer.ts:27", notes: "direct" },
        { field_name: "surplusAmount", expected_type: "double", nullable: false, backend_response_key: "surplus_amount", backend_source: "src/shared/utils/leadSerializer.ts:28", notes: "numeric conversion" },
        { field_name: "saleDate", expected_type: "DateTime", nullable: false, backend_response_key: "sale_date", backend_source: "src/shared/utils/leadSerializer.ts:29", notes: "ISO8601" },
        { field_name: "status", expected_type: "String(enum name)", nullable: false, backend_response_key: "status", backend_source: "src/shared/utils/leadSerializer.ts:30", notes: "must match LeadStatus.name" },
        { field_name: "lobVerificationStatus", expected_type: "String(enum name)", nullable: false, backend_response_key: "lob_verification_status", backend_source: "src/shared/utils/leadSerializer.ts:31", notes: "must match LobVerificationStatus.name" },
        { field_name: "lobAddressId", expected_type: "String", nullable: true, backend_response_key: "lob_address_id", backend_source: "src/shared/utils/leadSerializer.ts:32", notes: "nullable" },
        { field_name: "lobLetterId", expected_type: "String", nullable: true, backend_response_key: "lob_letter_id", backend_source: "src/shared/utils/leadSerializer.ts:33", notes: "nullable" },
        { field_name: "mailEvents", expected_type: "MailEvent[]", nullable: false, backend_response_key: "mail_events", backend_source: "src/shared/utils/leadSerializer.ts:43-47", notes: "defaults [] in flutter" },
        { field_name: "manualReviewRequired", expected_type: "bool", nullable: false, backend_response_key: "manual_review_required", backend_source: "src/shared/utils/leadSerializer.ts:34", notes: "default false in flutter" },
        { field_name: "legalReviewCleared", expected_type: "bool", nullable: false, backend_response_key: "legal_review_cleared", backend_source: "src/shared/utils/leadSerializer.ts:35", notes: "default false" },
        { field_name: "flaggedForLegalReview", expected_type: "bool", nullable: false, backend_response_key: "flagged_for_legal_review", backend_source: "src/shared/utils/leadSerializer.ts:36", notes: "default false" },
        { field_name: "assignmentConfidence", expected_type: "double", nullable: true, backend_response_key: "assignment_confidence", backend_source: "src/shared/utils/leadSerializer.ts:37", notes: "num?->double?" },
        { field_name: "dataSource", expected_type: "String", nullable: false, backend_response_key: "data_source", backend_source: "src/shared/utils/leadSerializer.ts:38", notes: "flutter fallback '' if missing" },
        { field_name: "sourceUrl", expected_type: "String", nullable: true, backend_response_key: "source_url", backend_source: "src/shared/utils/leadSerializer.ts:39", notes: "nullable" },
        { field_name: "activityLog", expected_type: "ActivityEntry[]", nullable: false, backend_response_key: "activity_log", backend_source: "src/shared/utils/leadSerializer.ts:48-53", notes: "defaults []" },
        { field_name: "notes", expected_type: "String", nullable: true, backend_response_key: "notes", backend_source: "src/shared/utils/leadSerializer.ts:40", notes: "nullable" },
        { field_name: "createdAt", expected_type: "DateTime", nullable: false, backend_response_key: "created_at", backend_source: "src/shared/utils/leadSerializer.ts:41", notes: "flutter fallback imported_at/now" },
        { field_name: "updatedAt", expected_type: "DateTime", nullable: false, backend_response_key: "updated_at", backend_source: "src/shared/utils/leadSerializer.ts:42", notes: "required by flutter parse" },
      ],
    },
  ],
  enum_reference_tables: {
    lead_status: {
      flutter_enum: "LeadStatus",
      backend_source: "src/shared/utils/statusMappings.ts:3-27",
      mapping: {
        IMPORTED: "imported",
        ADDRESS_VERIFIED: "addressVerified",
        LETTER_GENERATED: "letterGenerated",
        PENDING_APPROVAL: "pendingApproval",
        ON_HOLD: "onHold",
        APPROVED: "approved",
        SENT: "sent",
        DELIVERED: "delivered",
        RETURNED: "returned",
        FAILED: "failed",
      },
    },
    lob_verification_status: {
      flutter_enum: "LobVerificationStatus",
      backend_source: "src/shared/utils/statusMappings.ts:29-36",
      mapping: {
        NOT_STARTED: "notStarted",
        PENDING: "pending",
        VERIFIED: "verified",
        CORRECTED: "corrected",
        UNDELIVERABLE: "undeliverable",
        FAILED: "failed",
      },
    },
    mail_tracking_status: {
      flutter_usage: "MailEvent.event string",
      backend_source: "src/shared/utils/leadSerializer.ts:43-47, src/modules/tracking/tracking.router.ts:16-22",
      allowed_values: ["submitted", "mailed", "delivered", "returned", "in_transit"],
    },
    assignment_confidence: {
      flutter_usage: "double? assignmentConfidence",
      backend_source: "src/shared/utils/leadSerializer.ts:37",
      value_range: "0.0 to 1.0 expected",
      type: "number|null",
    },
    notification_types: {
      flutter_enum: "NotificationEventType",
      backend_source: "src/shared/utils/statusMappings.ts:38-44",
      mapping: {
        NEW_LEAD_READY: "newLeadReady",
        LETTER_RETURNED: "letterReturned",
        RECIPIENT_RESPONDED: "recipientResponded",
        LEGAL_REVIEW_REQUIRED: "legalReviewRequired",
        APPROVAL_COMPLETED: "approvalCompleted",
      },
    },
    state_county_identifiers: {
      flutter_source: "SourceState.abbr and supported county constants in lead.dart",
      backend_source: "prisma/schema.prisma:67-69 and lead serializer/router filters",
      states: ["CA", "FL"],
      supported_counties_phase1: {
        CA: ["Los Angeles", "Orange", "El Dorado", "Tulare"],
        FL: ["Lee", "Brevard"],
      },
    },
  },
  validation_summary: {
    fields_fully_matched: [
      "AuthUser fields",
      "Lead core + nested MailEvent/ActivityEntry fields",
      "DashboardStats fields",
      "NotificationEvent fields",
      "Lead/query endpoint signatures used by ApiService",
    ],
    fields_transformed: [
      "Lead.status DB enum -> Flutter LeadStatus.name",
      "Lead.lob_verification_status DB enum -> Flutter LobVerificationStatus.name",
      "Notification.type DB enum -> Flutter NotificationEventType.name",
      "Decimal surplusAmount -> numeric",
      "Date fields -> ISO8601 strings",
    ],
    assumptions_made: [
      "Letters queue uses Lead schema because Flutter parses with Lead.fromJson",
      "Mail tracking model in flutter uses event/timestamp/description pattern from lead.dart MailEvent",
    ],
    optional_fields: [
      "owner_phone",
      "owner_email",
      "lob_address_id",
      "lob_letter_id",
      "assignment_confidence",
      "source_url",
      "notes",
      "lead_owner_name",
      "message",
      "description",
    ],
    remaining_risks: [
      "No parser-time runtime validation script against real Flutter repo; contract report currently source-mapped manually",
      "If Flutter adds new fromJson fields, regen/check must be rerun",
    ],
  },
};

const out = path.join(process.cwd(), "contract_report.json");
fs.writeFileSync(out, stableStringify(report), "utf-8");
console.log(`Wrote ${out}`);
